import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            globals: {
                // Browser globals
                window: 'readonly',
                document: 'readonly',
                localStorage: 'readonly',
                location: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                console: 'readonly',
                navigator: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                btoa: 'readonly',
                unescape: 'readonly',
                encodeURIComponent: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                FileReader: 'readonly',
                Audio: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                clearTimeout: 'readonly',
                caches: 'readonly',
                Response: 'readonly',
                self: 'readonly',
                getComputedStyle: 'readonly',
                
                // Game engine globals (loaded via separate scripts in index.html)
                CONFIG: 'readonly',
                SaveManager: 'readonly',
                STAGES: 'readonly',
                STAGES_MAIN: 'readonly',
                STAGES_NORMAL: 'readonly',
                STAGES_EX: 'readonly',
                STAGES_EVENT: 'readonly',
                STAGES_CHAPTER2: 'readonly',
                STAGES_CHAPTER3: 'readonly',
                STAGES_CHAPTER4: 'readonly',
                STAGES_CHAPTER5: 'readonly',
                React: 'readonly',
                ReactDOM: 'readonly',
                _getCachedGradient: 'readonly',
                
                // Project scripts globals
                InputManager: 'readonly',
                Particle: 'readonly',
                ParticleSystem: 'readonly',
                ParticlePool: 'readonly',
                SoundManager: 'readonly',
                Physics: 'readonly',
                Renderer: 'readonly',
                SimpleProjectile: 'readonly',
                Projectile: 'readonly',
                AmmoItem: 'readonly',
                Cannon: 'readonly',
                AmmoDropper: 'readonly',
                Powerup: 'readonly',
                PowerupManager: 'readonly',
                Story: 'readonly',
                StoryManager: 'readonly',
                DefenderSlime: 'readonly',
                InvaderAI: 'readonly',
                AllySlime: 'readonly',
                Player: 'readonly',
                Laser: 'readonly',
                Fire: 'readonly',
                TankInterior: 'readonly',
                BattleManager: 'readonly',
                Stages: 'readonly',
                UI: 'readonly',
                TouchController: 'readonly',
                GMNarrator: 'readonly',
                Game: 'readonly',
                _getFrameNow: 'readonly',
                _tickFrameNow: 'readonly',
                saveSlimeScore: 'readonly',
                GmNarrator: 'readonly',
            },
            parserOptions: {
                ecmaVersion: 'latest',
                sourceType: 'module',
            }
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-undef': 'error',
            'no-cond-assign': 'error',
            'no-dupe-args': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['error', { 'allowEmptyCatch': true }],
            'no-extra-semi': 'error',
            'no-func-assign': 'error',
            'no-inner-declarations': 'error',
            'no-unreachable': 'error',
            'no-irregular-whitespace': ['error', { 'skipStrings': true }],
        }
    }
];
